### ISSUE TITLE
NewEvnClient doesn't work with manual setting environment variables

### ISSUE THREAD

**Issue by stt106** [leancloud/go-sdk#27]
```
      os.Setenv("LEANCLOUD_APP_ID", "*************")
	os.Setenv("LEANCLOUD_APP_KEY", "*************")
	os.Setenv("LEANCLOUD_APP_MASTER_KEY", "*************")
	os.Setenv("LEANCLOUD_API_SERVER", "*************")
	client := leancloud.NewEnvClient()
```

Not sure how to initialize the sdk; even with manually setting the required environment variables, it still throws: 
`"please set API's serverURL for China region or legacy app"`

**Comment by soasurs** [comment]
This issue is a bit complicated.

The LeanEngine part of Go SDK initializes a `client` in the package's `init()` function for LeanEngine related operations, such as remote calls to cloud functions, but this part of the `client` initialization is done by reading environment variables. So if you set environment variables in `main()`, it must be after `init()` is executed, and that's why the error is reported.

**Comment by stt106** [comment]
I had a quick look at the code and agree that `init()` is called to load the environment variables. 
So there is no easy fix for this?
Wonder how others have been using the go-sdk.

**Comment by jeffguorg** [comment]
by setting environment variables via direnv or similar tools, or using IDEs like Jetbrains and editors like vscode support setting environment variables in debug targets

for example I'm using vscode with this configuration:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/main.go",
            "envFile": "${workspaceFolder}/.env"
        }
    ]
}
```
